# Generated by Django 5.2.4 on 2025-07-31 14:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cajon',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('capacidad_maxima', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='TipoObjeto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('descripcion', models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='CajonHistorial',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateTimeField(auto_now_add=True)),
                ('accion', models.CharField(max_length=100)),
                ('descripcion', models.TextField(blank=True, null=True)),
                ('cajon', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='historial_entries', to='cajones_app.cajon')),
            ],
        ),
        migrations.AddField(
            model_name='cajon',
            name='historial',
            field=models.ManyToManyField(blank=True, related_name='cajones', to='cajones_app.cajonhistorial'),
        ),
        migrations.CreateModel(
            name='CajonObjeto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_objeto', models.CharField(max_length=100)),
                ('tamanio', models.CharField(choices=[('PE', 'Pequeño'), ('ME', 'Mediano'), ('GR', 'Grande')], default='PE', max_length=2)),
                ('cajon', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='objetos', to='cajones_app.cajon')),
                ('tipo_objeto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='objetos', to='cajones_app.tipoobjeto')),
            ],
        ),
    ]
