# Generated by Django 5.2.4 on 2025-07-31 16:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cajones_app', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cajon',
            name='historial',
        ),
    ]
